# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Work.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(908, 708)
        Form.setMaximumSize(QtCore.QSize(77000, 520000))
        self.pushButton_45 = QtWidgets.QPushButton(Form)
        self.pushButton_45.setGeometry(QtCore.QRect(-83, 8, 75, 23))
        self.pushButton_45.setText("")
        self.pushButton_45.setObjectName("pushButton_45")
        self.pushButton_49 = QtWidgets.QPushButton(Form)
        self.pushButton_49.setGeometry(QtCore.QRect(-83, 66, 75, 23))
        self.pushButton_49.setText("")
        self.pushButton_49.setObjectName("pushButton_49")
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 851, 691))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_multiply = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_multiply.setObjectName("pushButton_multiply")
        self.buttonGroup_binary = QtWidgets.QButtonGroup(Form)
        self.buttonGroup_binary.setObjectName("buttonGroup_binary")
        self.buttonGroup_binary.addButton(self.pushButton_multiply)
        self.gridLayout.addWidget(self.pushButton_multiply, 2, 8, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.buttonGroup_numbers = QtWidgets.QButtonGroup(Form)
        self.buttonGroup_numbers.setObjectName("buttonGroup_numbers")
        self.buttonGroup_numbers.addButton(self.pushButton_7)
        self.gridLayout.addWidget(self.pushButton_7, 2, 4, 1, 1)
        self.pushButton_cos = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_cos.setObjectName("pushButton_cos")
        self.gridLayout.addWidget(self.pushButton_cos, 3, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.buttonGroup_numbers.addButton(self.pushButton_4)
        self.gridLayout.addWidget(self.pushButton_4, 3, 4, 1, 1)
        self.pushButton_tan = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_tan.setObjectName("pushButton_tan")
        self.gridLayout.addWidget(self.pushButton_tan, 3, 3, 1, 1)
        self.widget = PlotWidget(self.gridLayoutWidget)
        self.widget.setObjectName("widget")
        self.gridLayout.addWidget(self.widget, 8, 0, 7, 5)
        self.pushButton_sqr_root = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_sqr_root.setObjectName("pushButton_sqr_root")
        self.gridLayout.addWidget(self.pushButton_sqr_root, 2, 1, 1, 1)
        self.pushButton_draw = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_draw.setObjectName("pushButton_draw")
        self.gridLayout.addWidget(self.pushButton_draw, 19, 3, 1, 1)
        self.pushButton_random = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_random.setObjectName("pushButton_random")
        self.gridLayout.addWidget(self.pushButton_random, 6, 3, 1, 1)
        self.line = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 7, 0, 1, 9)
        self.pushButton_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_1.setObjectName("pushButton_1")
        self.buttonGroup_numbers.addButton(self.pushButton_1)
        self.gridLayout.addWidget(self.pushButton_1, 4, 4, 1, 1)
        self.pushButton_square = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_square.setObjectName("pushButton_square")
        self.gridLayout.addWidget(self.pushButton_square, 1, 1, 1, 1)
        self.pushButton_tanh = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_tanh.setObjectName("pushButton_tanh")
        self.gridLayout.addWidget(self.pushButton_tanh, 4, 3, 1, 1)
        self.pushButton_AC = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_AC.setObjectName("pushButton_AC")
        self.gridLayout.addWidget(self.pushButton_AC, 1, 4, 1, 1)
        self.pushButton_equally = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_equally.setObjectName("pushButton_equally")
        self.buttonGroup_binary.addButton(self.pushButton_equally)
        self.gridLayout.addWidget(self.pushButton_equally, 6, 8, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.buttonGroup_numbers.addButton(self.pushButton_2)
        self.gridLayout.addWidget(self.pushButton_2, 4, 5, 1, 2)
        self.pushButton_factorial = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_factorial.setObjectName("pushButton_factorial")
        self.gridLayout.addWidget(self.pushButton_factorial, 2, 3, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 8, 5, 7, 1)
        self.lblSum = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblSum.setFont(font)
        self.lblSum.setObjectName("lblSum")
        self.gridLayout.addWidget(self.lblSum, 13, 6, 1, 2)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.buttonGroup_numbers.addButton(self.pushButton_3)
        self.gridLayout.addWidget(self.pushButton_3, 4, 7, 1, 1)
        self.pushButton_comma = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_comma.setObjectName("pushButton_comma")
        self.gridLayout.addWidget(self.pushButton_comma, 6, 7, 1, 1)
        self.pushButton_sin = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_sin.setObjectName("pushButton_sin")
        self.gridLayout.addWidget(self.pushButton_sin, 3, 1, 1, 1)
        self.pushButton_plus = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_plus.setObjectName("pushButton_plus")
        self.buttonGroup_binary.addButton(self.pushButton_plus)
        self.gridLayout.addWidget(self.pushButton_plus, 4, 8, 1, 1)
        self.pushButton_cube = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_cube.setObjectName("pushButton_cube")
        self.gridLayout.addWidget(self.pushButton_cube, 1, 2, 1, 1)
        self.spinBox_a = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_a.setObjectName("spinBox_a")
        self.gridLayout.addWidget(self.spinBox_a, 20, 1, 1, 1)
        self.pushButton_division = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_division.setObjectName("pushButton_division")
        self.buttonGroup_binary.addButton(self.pushButton_division)
        self.gridLayout.addWidget(self.pushButton_division, 1, 8, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 12, 6, 1, 2)
        self.pushButton_10x = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_10x.setObjectName("pushButton_10x")
        self.gridLayout.addWidget(self.pushButton_10x, 1, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.buttonGroup_numbers.addButton(self.pushButton_6)
        self.gridLayout.addWidget(self.pushButton_6, 3, 7, 1, 1)
        self.pushButton_exponentiation = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_exponentiation.setObjectName("pushButton_exponentiation")
        self.buttonGroup_binary.addButton(self.pushButton_exponentiation)
        self.gridLayout.addWidget(self.pushButton_exponentiation, 1, 3, 1, 1)
        self.pushButton_minus = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_minus.setObjectName("pushButton_minus")
        self.buttonGroup_binary.addButton(self.pushButton_minus)
        self.gridLayout.addWidget(self.pushButton_minus, 3, 8, 1, 1)
        self.btnResult = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnResult.setObjectName("btnResult")
        self.gridLayout.addWidget(self.btnResult, 11, 6, 1, 2)
        self.pushButton_plus_minus = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_plus_minus.setObjectName("pushButton_plus_minus")
        self.gridLayout.addWidget(self.pushButton_plus_minus, 1, 5, 1, 2)
        self.spinBox_b = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_b.setProperty("value", 10)
        self.spinBox_b.setObjectName("spinBox_b")
        self.gridLayout.addWidget(self.spinBox_b, 20, 2, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.buttonGroup_numbers.addButton(self.pushButton_8)
        self.gridLayout.addWidget(self.pushButton_8, 2, 5, 1, 2)
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.buttonGroup_numbers.addButton(self.pushButton_5)
        self.gridLayout.addWidget(self.pushButton_5, 3, 5, 1, 2)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setMaximumSize(QtCore.QSize(331, 16777215))
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 19, 1, 1, 2)
        self.pushButton_percent = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_percent.setObjectName("pushButton_percent")
        self.buttonGroup_binary.addButton(self.pushButton_percent)
        self.gridLayout.addWidget(self.pushButton_percent, 1, 7, 1, 1)
        self.pushButton_sinh = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_sinh.setObjectName("pushButton_sinh")
        self.gridLayout.addWidget(self.pushButton_sinh, 4, 1, 1, 1)
        self.pushButton_cosh = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_cosh.setObjectName("pushButton_cosh")
        self.gridLayout.addWidget(self.pushButton_cosh, 4, 2, 1, 1)
        self.pushButton_pi = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_pi.setObjectName("pushButton_pi")
        self.gridLayout.addWidget(self.pushButton_pi, 6, 2, 1, 1)
        self.txtNum2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtNum2.setFont(font)
        self.txtNum2.setMaxLength(2)
        self.txtNum2.setObjectName("txtNum2")
        self.gridLayout.addWidget(self.txtNum2, 10, 6, 1, 2)
        self.txtNum1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtNum1.setFont(font)
        self.txtNum1.setObjectName("txtNum1")
        self.gridLayout.addWidget(self.txtNum1, 9, 6, 1, 2)
        self.pushButton_cube_root = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_cube_root.setObjectName("pushButton_cube_root")
        self.gridLayout.addWidget(self.pushButton_cube_root, 2, 2, 1, 1)
        self.pushButton_0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_0.setObjectName("pushButton_0")
        self.buttonGroup_numbers.addButton(self.pushButton_0)
        self.gridLayout.addWidget(self.pushButton_0, 6, 4, 1, 3)
        self.pushButton_9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_9.setObjectName("pushButton_9")
        self.buttonGroup_numbers.addButton(self.pushButton_9)
        self.gridLayout.addWidget(self.pushButton_9, 2, 7, 1, 1)
        self.table = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.table.setFont(font)
        self.table.setObjectName("table")
        self.gridLayout.addWidget(self.table, 0, 3, 1, 6)
        self.pushButton_inverse_fraction = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_inverse_fraction.setObjectName("pushButton_inverse_fraction")
        self.gridLayout.addWidget(self.pushButton_inverse_fraction, 2, 0, 1, 1)
        self.pushButton_log = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_log.setObjectName("pushButton_log")
        self.gridLayout.addWidget(self.pushButton_log, 3, 0, 1, 1)
        self.pushButton_e = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_e.setObjectName("pushButton_e")
        self.gridLayout.addWidget(self.pushButton_e, 6, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Построение графика"))
        self.pushButton_45.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">:</span></p></body></html>"))
        self.pushButton_49.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">:</span></p></body></html>"))
        self.pushButton_multiply.setText(_translate("Form", "x"))
        self.pushButton_7.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">:</span></p></body></html>"))
        self.pushButton_7.setText(_translate("Form", "7"))
        self.pushButton_cos.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">:</span></p></body></html>"))
        self.pushButton_cos.setText(_translate("Form", "cos"))
        self.pushButton_4.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">:</span></p></body></html>"))
        self.pushButton_4.setText(_translate("Form", "4"))
        self.pushButton_tan.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">:</span></p></body></html>"))
        self.pushButton_tan.setText(_translate("Form", "tan"))
        self.pushButton_sqr_root.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">:</span></p></body></html>"))
        self.pushButton_sqr_root.setText(_translate("Form", "2√x"))
        self.pushButton_draw.setText(_translate("Form", "Построить"))
        self.pushButton_random.setText(_translate("Form", "Random"))
        self.pushButton_1.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">:</span></p></body></html>"))
        self.pushButton_1.setText(_translate("Form", "1"))
        self.pushButton_square.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\">x<span style=\" vertical-align:super;\">2</span></p></body></html>"))
        self.pushButton_square.setText(_translate("Form", "x^2"))
        self.pushButton_tanh.setText(_translate("Form", "tanh"))
        self.pushButton_AC.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">:</span></p></body></html>"))
        self.pushButton_AC.setText(_translate("Form", "AC"))
        self.pushButton_equally.setText(_translate("Form", "="))
        self.pushButton_2.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">:</span></p></body></html>"))
        self.pushButton_2.setText(_translate("Form", "2"))
        self.pushButton_factorial.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">:</span></p></body></html>"))
        self.pushButton_factorial.setText(_translate("Form", "x!"))
        self.lblSum.setText(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.pushButton_3.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">:</span></p></body></html>"))
        self.pushButton_3.setText(_translate("Form", "3"))
        self.pushButton_comma.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">:</span></p></body></html>"))
        self.pushButton_comma.setText(_translate("Form", "."))
        self.pushButton_sin.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">:</span></p></body></html>"))
        self.pushButton_sin.setText(_translate("Form", "sin"))
        self.pushButton_plus.setText(_translate("Form", "+"))
        self.pushButton_cube.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">:</span></p></body></html>"))
        self.pushButton_cube.setText(_translate("Form", "x^3"))
        self.pushButton_division.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">:</span></p></body></html>"))
        self.pushButton_division.setText(_translate("Form", ":"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">=</span></p></body></html>"))
        self.pushButton_10x.setText(_translate("Form", "10^x"))
        self.pushButton_6.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">:</span></p></body></html>"))
        self.pushButton_6.setText(_translate("Form", "6"))
        self.pushButton_exponentiation.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">:</span></p></body></html>"))
        self.pushButton_exponentiation.setText(_translate("Form", "x^y"))
        self.pushButton_minus.setText(_translate("Form", "-"))
        self.btnResult.setText(_translate("Form", "Выполнить"))
        self.pushButton_plus_minus.setText(_translate("Form", "±"))
        self.pushButton_8.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">:</span></p></body></html>"))
        self.pushButton_8.setText(_translate("Form", "8"))
        self.pushButton_5.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">:</span></p></body></html>"))
        self.pushButton_5.setWhatsThis(_translate("Form", "<html><head/><body><p>5</p></body></html>"))
        self.pushButton_5.setText(_translate("Form", "5"))
        self.pushButton_percent.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">:</span></p></body></html>"))
        self.pushButton_percent.setText(_translate("Form", "%"))
        self.pushButton_sinh.setText(_translate("Form", "sinh"))
        self.pushButton_cosh.setText(_translate("Form", "cosh"))
        self.pushButton_pi.setText(_translate("Form", "pi"))
        self.txtNum2.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Система счисления от </span><span style=\" font-size:12pt; font-weight:600;\">2</span><span style=\" font-size:12pt;\"> до </span><span style=\" font-size:12pt; font-weight:600;\">36</span><span style=\" font-size:12pt;\">!</span></p></body></html>"))
        self.txtNum1.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Введите число в системе счисления от </span><span style=\" font-size:12pt; font-weight:600;\">2</span><span style=\" font-size:12pt;\"> до </span><span style=\" font-size:12pt; font-weight:600;\">36</span><span style=\" font-size:12pt;\"> и результат будет в </span><span style=\" font-size:12pt; font-weight:600;\">10</span><span style=\" font-size:12pt;\">-ной сс.</span></p></body></html>"))
        self.pushButton_cube_root.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">:</span></p></body></html>"))
        self.pushButton_cube_root.setText(_translate("Form", "3√x"))
        self.pushButton_0.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">:</span></p></body></html>"))
        self.pushButton_0.setText(_translate("Form", "0"))
        self.pushButton_9.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">:</span></p></body></html>"))
        self.pushButton_9.setText(_translate("Form", "9"))
        self.table.setText(_translate("Form", "<html><head/><body><p align=\"right\"><span style=\" font-size:64pt;\"><br/></span></p></body></html>"))
        self.pushButton_inverse_fraction.setText(_translate("Form", "1/x"))
        self.pushButton_log.setText(_translate("Form", "log"))
        self.pushButton_e.setText(_translate("Form", "e"))

from pyqtgraph import PlotWidget
